### ISSUE TITLE
Clarify license 

### ISSUE THREAD

**Issue by CosmicHorrorDev** [greggb/sublime-snazzy#2]
Hiya! I really love this theme, and I was wondering if you could clarify under what terms/license all of this is released under? I've got a project that winds up embedding this theme as one of default options

**Comment by greggb** [comment]
Hey, thanks for raising this. Just added the LICENSE file with an MIT license. Hope that helps!

**Comment by CosmicHorrorDev** [comment]
That's clears things up perfectly. Thanks :)

And just for fun here's how the theme looks in [`inlyne`](https://github.com/Inlyne-Project/inlyne) which is a markdown viewer that I help maintain

![image](https://github.com/greggb/sublime-snazzy/assets/30302768/298857f3-82fe-4afc-85bc-1cdd2e1b2490)

although I originally found your theme because [`bat`](https://github.com/sharkdp/bat) bundles it in their default set
